name: stride
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - blosc
  - cached-property
  - click
  - cloudpickle>=1.6
  - cython
  - dash>=2.0.0
  - flake8
  - gputil
  - h5py>=3.2
  - matplotlib>=3.4
  - multiprocess
  - nbval
  - numpy>=1.20
  - notebook>=6.4
  - pip
  - pre-commit>=2.13
  - psutil
  - pyface
  - pyflakes
  - pytest
  - pytest-cov
  - pyyaml>=5.4
  - pyqt5-sip
  - pytest-runner
  - pyzmq>=22.1
  - scikit-image
  - scipy>=1.6
  - sphinx
  - sphinx_rtd_theme
  - tornado>=6.1
  - traitsui
  - uvloop
  - zlib
  - zict>=3.0.0
  - pip:
      - devito>=4.6
      - python-daemon
      - py-libnuma
      - tblib
      - resampy
